# Generated by Django 4.2.5 on 2023-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=180)),
                ('target', models.CharField(choices=[('pembejeo', 'Pembejeo'), ('huduma za kitaalamu', 'Huduma za Kitaalamu')], max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
