# Generated by Django 4.2.5 on 2023-09-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima_digital_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembejeo', models.CharField(max_length=180)),
                ('huduma', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkulima_digital_api.target'),
        ),
    ]
