# Generated by Django 4.2.5 on 2023-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima_digital_api', '0002_target_alter_feedback_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='huduma',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='pembejeo',
        ),
    ]
