# Generated by Django 4.2.5 on 2023-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima_digital_api', '0004_pembejeo_feedback_pembejeo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='pembejeo_desc',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='pembejeo',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ushauri_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Pembejeo',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
