# Generated by Django 4.2.5 on 2023-09-30 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima_digital_api', '0005_rename_description_feedback_pembejeo_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pembejeo_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
